from properties import *
from constants import *

prop_json = {"properties": [
    {"id": 0,
    "name": "GO",
    "type": GO,
    "locx": card_length + 19*(card_breadth/2),
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y1": gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh},
    {"id": 1,
    "name": "Mediteranean Avenue",
    "type": PROPERTY,
    "cost": 60,
    "baseRent": 2,
    "monopolyRent": 4, 
    "rent": (2, 10, 30, 90, 160, 250),
    "buildCost": 50,
    "mortgage": 30,
    "set": [1, 3],
    "color": brown,
    "locx": card_length + 17*(card_breadth/2),
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y1": gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh},
    {"id": 2,
    "name": "Community Chest",
    "type": CHEST,
    "locx": card_length + 15*(card_breadth/2),
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y1": gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh},
    {"id": 3,
    "name": "Baltic Avenue",
    "type": PROPERTY,
    "cost": 60,
    "baseRent": 4,
    "monopolyRent": 8,
    "rent": (4, 10, 30, 90, 160, 250),
    "buildCost": 50,
    "mortgage": 30,
    "set": [1, 3],
    "color": brown,
    "locx": card_length + 13*(card_breadth/2),
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2+  c2gaph,
    "y1": gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2": display_height + gaph + boxb/2+ c2gaph,
    "y2": 2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh},
    {"id": 4,
    "name": "Income Tax",
    "type": INCTAX,
    "locx": card_length + 11 * (card_breadth/2),
    "locy":  display_height - card_length/2,
    "x1":  display_height + gaph + boxb/2 + 2*c2gaph + cardl,
    "y1":  gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2":  display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y2":  2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh},
    {"id": 5,
    "name": "Reading Railroad",
    "type": RAIL,
    "cost": 200,
    "rent": (25, 50, 100, 200),
    "mortgage": 100,
    "set": [5, 15, 25, 35],
    "color": black,
    "locx": card_length + 9*card_breadth/2,
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2+  c3gaph,
    "y1": gapv + 0.2*boxl + 5*cgapv + 4*cardh,
    "x2": display_height + gaph + boxb/2+ c3gaph,
    "y2": 2*gapv + boxl + 0.2*boxl + 5*cgapv + 4*cardh},
    {"id": 6,
    "name": "Oriental Avenue",
    "type": PROPERTY,
    "cost": 100,
    "baseRent": 6,
    "monopolyRent": 12,
    "rent": (6, 30, 90, 270, 400, 550),
    "buildCost": 50,
    "mortgage": 50,
    "set": [6, 8, 9],
    "color": lightblue,
    "locx": card_length + 7*(card_breadth/2),
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2 + 3*cgaph + 2*cardl,
    "y1": gapv + 0.2*boxl + 3*cgapv + 2*cardh,
    "x2": display_height + gaph + boxb/2 + 3*cgaph + 2*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 3*cgapv + 2*cardh},
    {"id": 7,
    "name": "Chance",
    "type": CHANCE,
    "locx": card_length + 5*(card_breadth/2),
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y1": gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh},
    {"id": 8,
    "name": "Vermont Avenue",
    "type": PROPERTY,
    "cost": 100,
    "baseRent": 6,
    "monopolyRent": 12,
    "rent": (6, 30, 90, 270, 400, 550),
    "buildCost": 50,
    "mortgage": 50,
    "set": [6, 8, 9],
    "color": lightblue,
    "locx": card_length + 3*(card_breadth/2),
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2 + 2*cgaph + cardl,
    "y1": gapv + 0.2*boxl + 3*cgapv + 2*cardh,
    "x2": display_height + gaph + boxb/2 + 2*cgaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 3*cgapv + 2*cardh},
    {"id": 9,
    "name": "Connecticut Avenue",
    "type": PROPERTY,
    "cost": 120,
    "baseRent": 8,
    "monopolyRent": 16,
    "rent": (8, 40, 100, 300, 450, 600),
    "buildCost": 50,
    "mortgage": 60,
    "set": [6, 8, 9],
    "color": lightblue,
    "locx": card_length + 1*(card_breadth/2),
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2 + cgaph,
    "y1": gapv + 0.2*boxl + 3*cgapv + 2*cardh,
    "x2": display_height + gaph + boxb/2 + cgaph,
    "y2": 2*gapv + boxl + 0.2*boxl + 3*cgapv + 2*cardh},
    {"id": 10,
    "name": "Just Visiting",
    "type": NONE,
    "locx": card_length - (card_breadth/2),
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y1": gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh},
    {"id": 11,
    "name": "St. Charles Place",
    "type": PROPERTY,
    "cost": 140,
    "baseRent": 10,
    "monopolyRent": 20,
    "rent": (10, 50, 150, 450, 625, 750),
    "buildCost": 100,
    "mortgage": 70,
    "set": [11, 13, 14],
    "color": magenta,
    "locx": card_length/2,
    "locy": card_length + 17*(card_breadth/2),
    "x1": display_height + gaph + 3*cgaph + 2*cardl,
    "y1": gapv + 0.2*boxl + 3*cgapv + 2*cardh,
    "x2": display_height + gaph + 3*cgaph + 2*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 3*cgapv + 2*cardh},
    {"id": 12,
    "name": "Electric Company",
    "type": UTILITY,
    "cost": 150,
    "mortgage": 75,
    "set": [12, 28],
    "locx": card_length/2,
    "locy": 7*card_breadth+card_breadth/2+card_length,
    "x1": display_height + gaph + c2gaph,
    "y1": gapv + 0.2*boxl + 5*cgapv + 4*cardh,
    "x2": display_height + gaph + c2gaph,
    "y2": 2*gapv + boxl + 0.2*boxl + 5*cgapv + 4*cardh},
    {"id": 13,
    "name": "States Avenue",
    "type": PROPERTY,
    "cost": 140,
    "baseRent": 10,
    "monopolyRent": 20,
    "rent": (10, 50, 150, 450, 625, 750),
    "buildCost": 100,
    "mortgage": 70,
    "set": [11, 13, 14],
    "color": magenta,
    "locx": card_length/2,
    "locy": card_length + 13*(card_breadth/2),
    "x1": display_height + gaph + 2*cgaph + cardl,
    "y1": gapv + 0.2*boxl +3*cgapv + 2*cardh,
    "x2": display_height + gaph + 2*cgaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 3*cgapv + 2*cardh},
    {"id": 14,
    "name": "Virginia Avenue",
    "type": PROPERTY,
    "cost": 160,
    "baseRent": 12,
    "monopolyRent": 24,
    "rent": (12, 60, 180, 500, 700, 900),
    "buildCost": 100,
    "mortgage": 80,
    "set": [11, 13, 14],
    "color": magenta,
    "locx": card_length/2,
    "locy": card_length + 11*(card_breadth/2),
    "x1": display_height + gaph + cgaph,
    "y1": gapv + 0.2*boxl + 3*cgapv + 2*cardh,
    "x2": display_height + gaph +2*cgapv + cardh,
    "y2": 2*gapv + boxl + 0.2*boxl + 3*cgapv + 2*cardh},
    {"id": 15,
    "name": "Pennsylvania Railroad",
    "type": RAIL,
    "cost": 200,
    "rent": (25, 50, 100, 200),
    "mortgage": 100,
    "set": [5, 15, 25, 35],
    "color": black,
    "locx": card_length/2,
    "locy": card_length + 9*card_breadth/2,
    "x1": display_height + gaph + boxb/2+  2*c3gaph + cardl,
    "y1": gapv + 0.2*boxl + 5*cgapv + 4*cardh,
    "x2": display_height + gaph + boxb/2+ 2*c3gaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 5*cgapv + 4*cardh},
    {"id": 16,
    "name": "St. James Place",
    "type": PROPERTY,
    "cost": 180,
    "baseRent": 14,
    "monopolyRent": 28,
    "rent": (14, 70, 200, 550, 750, 950),
    "buildCost": 100,
    "mortgage": 90,
    "set": [16, 18, 19],
    "color": orange,
    "locx": card_length/2,
    "locy": card_length + 7*(card_breadth/2),
    "x1": display_height + gaph + boxb/2 + 3*cgaph + 2*cardl,
    "y1": gapv + 0.2*boxl + 2*cgapv + cardh,
    "x2": display_height + gaph + boxb/2 + 3*cgaph + 2*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 2*cgapv + cardh},
    {"id": 17,
    "name": "Community Chest",
    "type": CHEST,
    "locx": card_length/2,
    "locy": card_length + 5*(card_breadth/2),
    "x1": display_height + gaph + boxb/2 + 3*cgaph + 2*cardl,
    "y1": gapv + 0.2*boxl + 2*cgapv + cardh,
    "x2": display_height + gaph + boxb/2 + 3*cgaph + 2*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 2*cgapv + cardh},
    {"id": 18,
    "name": "Tennessee Avenue",
    "type": PROPERTY,
    "cost": 180,
    "baseRent": 14,
    "monopolyRent": 28,
    "rent": (14, 70, 200, 550, 750, 950),
    "buildCost": 100,
    "mortgage": 90,
    "set": [16, 18, 19],
    "color": orange,
    "locx": card_length/2,
    "locy": card_length + 3*(card_breadth/2),
    "x1": 50000,
    "y1": display_height + gaph + boxb/2 + 2*cgaph + cardl,
    "x2": gapv + 0.2*boxl + 2*cgapv + cardh,
    "y2": display_height + gaph + boxb/2 + 2*cgaph + cardl},
    {"id": 19,
    "name": "New York Avenue",
    "type": PROPERTY,
    "cost": 200,
    "baseRent": 16,
    "monopolyRent": 32,
    "rent": (16, 80, 220, 600, 800, 1000),
    "buildCost": 100,
    "mortgage": 100,
    "set": [16, 18, 19],
    "color": orange,
    "locx": card_length/2,
    "locy": card_length + 1*(card_breadth/2),
    "x1": display_height + gaph + boxb/2 + cgaph,
    "y1": gapv + 0.2*boxl + 2*cgapv + cardh,
    "x2": display_height + gaph + boxb/2 + cgaph,
    "y2": 2*gapv + boxl + 0.2*boxl + 2*cgapv + cardh},
    {"id": 20,
    "name": "Free Parking",
    "type": NONE,
    "locx": card_length/2,
    "locy": card_length/2,
    "x1": display_height + gaph + boxb/2 + cgaph,
    "y1": gapv + 0.2*boxl + 2*cgapv + cardh,
    "x2": display_height + gaph + boxb/2 + cgaph,
    "y2": 2*gapv + boxl + 0.2*boxl + 2*cgapv + cardh},
    {"id": 21,
    "name": "Kentucky Avenue",
    "type": PROPERTY,
    "cost": 220,
    "baseRent": 18,
    "monopolyRent": 36,
    "rent": (18, 90, 250, 700, 875, 1050),
    "buildCost": 150,
    "mortgage": 110,
    "set": [21, 23, 24],
    "color": red,
    "locx": card_length + card_breadth/2,
    "locy": card_length/2,
    "x1": display_height + gaph + cgaph,
    "y1": gapv + 0.2*boxl + cgapv,
    "x2": display_height + gaph + cgaph,
    "y2": 2*gapv + boxl + 0.2*boxl + cgapv},
    {"id": 22,
    "name": "Chance",
    "type": CHANCE,
    "locx": card_length + 3*(card_breadth/2),
    "locy": card_length/2,
    "x1": display_height + gaph + cgaph,
    "y1": gapv + 0.2*boxl + cgapv,
    "x2": display_height + gaph + cgaph,
    "y2": 2*gapv + boxl + 0.2*boxl + cgapv},
    {"id": 23,
    "name": "Indiana Avenue",
    "type": PROPERTY,
    "cost": 220,
    "baseRent": 18,
    "monopolyRent": 36,
    "rent": (18, 90, 250, 700, 875, 1050),
    "buildCost": 150,
    "mortgage": 110,
    "set": [21, 23, 24],
    "color": red,
    "locx": card_length + 5*(card_breadth/2),
    "locy": card_length/2,
    "x1": display_height + gaph + 2*cgaph + cardl,
    "y1": gapv + 0.2*boxl + cgapv,
    "x2": display_height + gaph + 2*cgaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + cgapv},
    {"id": 24,
    "name": "Illinois Avenue",
    "type": PROPERTY,
    "cost": 240,
    "baseRent": 20,
    "monopolyRent": 40,
    "rent": (20, 100, 300, 750, 925, 1100),
    "buildCost": 120,
    "mortgage": 120,
    "set": [21, 23, 24],
    "color": red,
    "locx": card_length + 7*(card_breadth/2),
    "locy": card_length/2,
    "x1": display_height + gaph + 3*cgaph + 2*cardl,
    "y1": gapv + 0.2*boxl + cgapv,
    "x2": display_height + gaph + 3*cgaph + 2*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + cgapv},
    {"id": 25,
    "name": "B & O. Railroad",
    "type": RAIL,
    "cost": 200,
    "rent": (25, 50, 100, 200),
    "mortgage": 100,
    "set": [5, 15, 25, 35],
    "color": black,
    "locx": card_length + 9*card_breadth/2,
    "locy": card_length/2,
    "x1": display_height + gaph + boxb/2+  3*c3gaph + 2*cardl,
    "y1": gapv + 0.2*boxl + 5*cgapv + 4*cardh,
    "x2": display_height + gaph + boxb/2+ 3*c3gaph + 2*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 5*cgapv + 4*cardh},
    {"id": 26,
    "name": "Atlantic Avenue",
    "type": PROPERTY,
    "cost": 260,
    "baseRent": 22,
    "monopolyRent": 44,
    "rent": (22, 110, 330, 800, 975, 1150),
    "buildCost": 150,
    "mortgage": 130,
    "set": [26, 27, 29],
    "color": yellow,
    "locx": card_length + 11*(card_breadth/2),
    "locy": card_length/2,
    "x1": display_height + gaph + boxb/2 + cgaph,
    "y1": gapv + 0.2*boxl + cgapv,
    "x2": display_height + gaph + boxb/2 + cgaph,
    "y2": 2*gapv + boxl + 0.2*boxl + cgapv},
    {"id": 27,
    "name": "Ventnor Avenue",
    "type": PROPERTY,
    "cost": 260,
    "baseRent": 22,
    "monopolyRent": 44,
    "rent": (22, 110, 330, 800, 975, 1150),
    "buildCost": 150,
    "mortgage": 130,
    "set": [26, 27, 29],
    "color": yellow,
    "locx": card_length + 13*(card_breadth/2),
    "locy": card_length/2,
    "x1": display_height + gaph + boxb/2 + 2*cgaph + cardl,
    "y1": gapv + 0.2*boxl + cgapv,
    "x2": display_height + gaph + boxb/2 + 2*cgaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + cgapv},
    {"id": 28,
    "name": "Water Works",
    "type": UTILITY,
    "cost": 150,
    "mortgage": 75,
    "set": [12, 28],
    "locx": 7*card_breadth+card_breadth/2+card_length,
    "locy": card_length/2,
    "x1": display_height + gaph + 2*c2gaph + cardl,
    "y1": gapv + 0.2*boxl + 5*cgapv + 4*cardh,
    "x2": display_height + gaph + 2*c2gaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 5*cgapv + 4*cardh},
    {"id": 29,
    "name": "Marvin Gardens",
    "type": PROPERTY,
    "cost": 280,
    "baseRent": 24,
    "monopolyRent": 48,
    "rent": (24, 120, 360, 850, 1025, 1200),
    "buildCost": 150,
    "mortgage": 140,
    "set": [26, 27, 29],
    "color": yellow,
    "locx": card_length + 17*(card_breadth/2),
    "locy": card_length/2,
    "x1": display_height + gaph + boxb/2 + 3*cgaph + 2*cardl,
    "y1": gapv + 0.2*boxl + cgapv,
    "x2": display_height + gaph + boxb/2 + 3*cgaph + 2*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + cgapv},
    {"id": 30,
    "name": "Go to Jail",
    "type": TOJAIL,
    "locx": card_length + 19*(card_breadth/2),
    "locy": card_length/2,
    "x1": display_height + gaph + boxb/2 + 3*cgaph + 2*cardl,
    "y1": gapv + 0.2*boxl + cgapv,
    "x2": display_height + gaph + boxb/2 + 3*cgaph + 2*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + cgapv},
    {"id": 31,
    "name": "Pacific Avenue",
    "type": PROPERTY,
    "cost": 300,
    "baseRent": 26,
    "monopolyRent": 52,
    "rent": (26, 130, 390, 900, 1100, 1275),
    "buildCost": 200,
    "mortgage": 150,
    "set": [31, 32, 34],
    "color": green,
    "locx": display_height -  card_length/2,
    "locy": card_length + 1*(card_breadth/2) ,
    "x1": display_height + gaph + cgaph,
    "y1": gapv + 0.2*boxl + 2*cgapv + cardh,
    "x2": display_height + gaph +2*cgapv + cardh,
    "y2": 2*gapv + boxl + 0.2*boxl + 2*cgapv + cardh},
    {"id": 32,
    "name": "North Carolina Avenue",
    "type": PROPERTY,
    "cost": 300,
    "baseRent": 26,
    "monopolyRent": 52,
    "rent": (26, 130, 390, 900, 1100, 1275),
    "buildCost": 200,
    "mortgage": 150,
    "set": [31, 32, 34],
    "color": green,
    "locx": display_height -  card_length/2,
    "locy": card_length + 3*(card_breadth/2),
    "x1": display_height + gaph + 2*cgaph + cardl,
    "y1": gapv + 0.2*boxl + 2*cgapv + cardh,
    "x2": display_height + gaph + 2*cgaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 2*cgapv + cardh},
    {"id": 33,
    "name": "Community Chest",
    "type": CHEST,
    "locx": display_height -  card_length/2,
    "locy": card_length + 5*(card_breadth/2),
    "x1": display_height + gaph + 2*cgaph + cardl,
    "y1": gapv + 0.2*boxl + 2*cgapv + cardh,
    "x2": display_height + gaph + 2*cgaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 2*cgapv + cardh},
    {"id": 34,
    "name": "Pennsylvania Avenue",
    "type": PROPERTY,
    "cost": 320,
    "baseRent": 28,
    "monopolyRent": 56,
    "rent": (28, 150, 450, 1000, 1200, 1400),
    "buildCost": 200,
    "mortgage": 160,
    "set": [31, 32, 34],
    "color": green,
    "locx": display_height -  card_length/2,
    "locy": card_length + 7*(card_breadth/2),
    "x1": display_height + gaph + 3*cgaph + 2*cardl,
    "y1": gapv + 0.2*boxl + 2*cgapv + cardh,
    "x2": display_height + gaph + 3*cgaph + 2*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 2*cgapv + cardh},
    {"id": 35,
    "name": "Short Line",
    "type": RAIL,
    "cost": 200,
    "rent": (25, 50, 100, 200),
    "mortgage": 100,
    "set": [5, 15, 25, 35],
    "color": black,
    "locx": display_height - card_length/2,
    "locy": card_length + 9*card_breadth/2,
    "x1": display_height + gaph + boxb/2+  4*c3gaph + 3*cardl,
    "y1": gapv + 0.2*boxl + 5*cgapv + 4*cardh,
    "x2": display_height + gaph + boxb/2+ 4*c3gaph + 3*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 5*cgapv + 4*cardh},
    {"id": 36,
    "name": "Chance",
    "type": CHANCE,
    "locx": display_height - card_length/2,
    "locy": card_length + 11*card_breadth/2,
    "x1": display_height + gaph + boxb/2+  4*c3gaph + 3*cardl,
    "y1": gapv + 0.2*boxl + 5*cgapv + 4*cardh,
    "x2": display_height + gaph + boxb/2+ 4*c3gaph + 3*cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 5*cgapv + 4*cardh},
    {"id": 37,
    "name": "Park Place",
    "type": PROPERTY,
    "cost": 350,
    "baseRent": 35,
    "monopolyRent": 70,
    "rent": (35, 175, 500, 1100, 1300, 1500),
    "buildCost": 200,
    "mortgage": 175,
    "set": [37, 39],
    "color": blue,
    "locx": display_height - card_length/2,
    "locy": card_length + 13*(card_breadth/2),
    "x1": display_height + gaph + c2gaph,
    "y1": gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2": display_height + gaph + c2gaph,
    "y2": 2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh},
    {"id": 38,
    "name": "Luxury Tax",
    "type": LUXTAX,
    "locx": display_height - card_length/2,
    "locy": card_length + 15*(card_breadth/2),
    "x1": display_height + gaph + c2gaph,
    "y1": gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2": display_height + gaph + c2gaph,
    "y2": 2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh},
    {"id": 39,
    "name": "Boardwalk",
    "type": PROPERTY,
    "cost": 400,
    "monopolyRent": 100,
    "rent": (50, 200, 600, 1400, 1700, 2000),
    "buildCost": 200,
    "mortgage": 200,
    "set": [37, 39],
    "color": blue,
    "locx": display_height - card_length/2,
    "locy": card_length + 17*(card_breadth/2),
    "x1": display_height + gaph + 2*c2gaph + cardl,
    "y1": gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2": display_height + gaph + 2*c2gaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh},
    {"id": 40,
    "name": "Jail",
    "type": None,
    "locx": card_length - (card_breadth/2),
    "locy": display_height - card_length/2,
    "x1": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y1": gapv + 0.2*boxl + 4*cgapv + 3*cardh,
    "x2": display_height + gaph + boxb/2+ 2*c2gaph + cardl,
    "y2": 2*gapv + boxl + 0.2*boxl + 4*cgapv + 3*cardh}
]}
    
properties = []
for prop in prop_json["properties"]:
    if prop["type"] == PROPERTY:
        properties.append(Property(prop["name"], prop["color"], prop["id"], prop["locx"], prop["locy"], prop["cost"], prop["x1"], prop["y1"], prop["x2"], prop["y2"], prop["rent"], prop["monopolyRent"], prop["buildCost"], prop["mortgage"], prop["set"]))
    elif prop["type"] == RAIL:
        properties.append(special_cards(prop["name"], prop["id"], prop["cost"], prop["locx"], prop["locy"], prop["x1"], prop["y1"], prop["x2"], prop["y2"], prop["rent"], prop["mortgage"], RAIL, prop["set"]))
    elif prop["type"] == UTILITY:
        properties.append(special_cards(prop["name"], prop["id"], prop["cost"], prop["locx"], prop["locy"], prop["x1"], prop["y1"], prop["x2"], prop["y2"], None, prop["mortgage"], UTILITY, prop["set"]))
    else:
        properties.append(extra_card(prop["name"], prop["id"], prop["type"], prop["locx"], prop["locy"], prop["x1"], prop["y1"], prop["x2"], prop["y2"]))




